function [params_ud, params_const] = LD1_PARAMS_FROM_CONFIG(domain_cfg, particles_cfg, fluid_cfg)
%LD1_PARAMS_FROM_CONFIG Build LD1 runtime parameter tables from JSON config.
%   [PARAMS_UD, PARAMS_CONST] = UTILS.LD1_PARAMS_FROM_CONFIG(...) converts
%   compact LD1 config sections into the legacy table shapes consumed by
%   TRANSP.INIT_DOM, PAR.INIT_DIAM, PAR.INIT_LOC, and TRANSP.MARCH.

if nargin < 1 || ~isstruct(domain_cfg)
    error('PFAL:LD1_PARAMS_FROM_CONFIG:MissingDomain', ...
        'transport.domain must be a struct.');
end
if nargin < 2 || ~isstruct(particles_cfg)
    error('PFAL:LD1_PARAMS_FROM_CONFIG:MissingParticles', ...
        'transport.particles must be a struct.');
end
if nargin < 3 || ~isstruct(fluid_cfg)
    error('PFAL:LD1_PARAMS_FROM_CONFIG:MissingFluid', ...
        'transport.fluid must be a struct.');
end

volume_fraction = require_scalar_field(domain_cfg, 'volume_fraction', ...
    'transport.domain.volume_fraction');
domain_size = require_vector_field(domain_cfg, 'size', 3, ...
    'transport.domain.size');

n_par = require_scalar_field(particles_cfg, 'n_par', ...
    'transport.particles.n_par');
n_pp_mean = require_scalar_field(particles_cfg, 'n_pp_mean', ...
    'transport.particles.n_pp_mean');
n_pp_std = require_scalar_field(particles_cfg, 'n_pp_std', ...
    'transport.particles.n_pp_std');
d_pp_gm = require_scalar_field(particles_cfg, 'd_pp_gm', ...
    'transport.particles.d_pp_gm');
d_pp_gsd_between = require_scalar_field(particles_cfg, ...
    'd_pp_gsd_between_aggregates', ...
    'transport.particles.d_pp_gsd_between_aggregates');
d_pp_gsd_within = require_scalar_field(particles_cfg, ...
    'd_pp_gsd_within_aggregates', ...
    'transport.particles.d_pp_gsd_within_aggregates');

temperature = require_scalar_field(fluid_cfg, 'temperature', ...
    'transport.fluid.temperature');
velocity = require_vector_field(fluid_cfg, 'velocity', 3, ...
    'transport.fluid.velocity');
pressure = require_scalar_field(fluid_cfg, 'pressure', ...
    'transport.fluid.pressure');

Name = {'volf'; 'dom_size(1)'; 'dom_size(2)'; 'dom_size(3)'; ...
    'n_par'; 'n_pp(1)'; 'n_pp(2)'; 'd_pp(1)'; 'd_pp(2)'; ...
    'd_pp(3)'; 'temp_f'; 'v_f(1)'; 'v_f(2)'; 'v_f(3)'; 'p_f'};
Value = [volume_fraction; domain_size(:); n_par; n_pp_mean; n_pp_std; ...
    d_pp_gm; d_pp_gsd_between; d_pp_gsd_within; temperature; ...
    velocity(:); pressure];
Unit = {'[-]'; '[m]'; '[m]'; '[m]'; '[-]'; '[-]'; '[-]'; '[m]'; ...
    '[-]'; '[-]'; '[K]'; '[m/s]'; '[m/s]'; '[m/s]'; '[Pa]'};
Description = {'Particle volume fraction'; 'Computational domain length'; ...
    'Computational domain width'; 'Computational domain height'; ...
    'Total number of initial particles'; ...
    'Mean number of primaries within the aggregates'; ...
    'Standard deviation of primary particle numbers within the aggregates'; ...
    'Global geometric mean size of primaries'; ...
    'Geometric standard deviation of primary particle size variations between aggregates'; ...
    'Geometric standard deviation of primary particle size variations within aggregates'; ...
    'Flow temperature'; 'Flow x velocity'; 'Flow y velocity'; ...
    'Flow z velocity'; 'Flow pressure'};
params_ud = table(Name, Value, Unit, Description);

Name = {'rho_bc'; 'M_air'; 'kb'; 'Na'; 'Ru'};
Value = [1.86e3; 28.97e-3; 1.381e-23; 6.022e23; 8.314];
Unit = {'kg/m3'; 'kg/mol'; 'j/k'; 'mol^-1'; 'j/mol.k'};
Description = {'Black Carbon bulk density'; 'Air molar mass'; ...
    'Boltzmann constant'; 'Avogadro constant'; 'Universal gas constant'};
params_const = table(Name, Value, Unit, Description);

end

function out = require_scalar_field(src, field_name, label)
if ~isfield(src, field_name) || isempty(src.(field_name))
    error('PFAL:LD1_PARAMS_FROM_CONFIG:MissingScalar', ...
        'The LD1 config is missing %s.', label);
end
out = double(src.(field_name));
if ~isscalar(out) || ~isfinite(out)
    error('PFAL:LD1_PARAMS_FROM_CONFIG:InvalidScalar', ...
        'The LD1 config field %s must be a finite numeric scalar.', label);
end
end

function out = require_vector_field(src, field_name, expected_len, label)
if ~isfield(src, field_name) || isempty(src.(field_name))
    error('PFAL:LD1_PARAMS_FROM_CONFIG:MissingVector', ...
        'The LD1 config is missing %s.', label);
end
out = double(src.(field_name));
out = reshape(out, 1, []);
if numel(out) ~= expected_len || any(~isfinite(out))
    error('PFAL:LD1_PARAMS_FROM_CONFIG:InvalidVector', ...
        'The LD1 config field %s must be a finite numeric vector of length %d.', ...
        label, expected_len);
end
end
